
server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://47.107.74.180:3306/dataentry?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root802711
    driver-class-name: com.mysql.cj.jdbc.Driver

  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

  #热部署文件，页面不产生缓存，及时更新
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
      cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
